### ISSUE TITLE
Querying a Hash using object properties

### ISSUE THREAD

**Issue by HaythemJ** [thepirat000/CachingFramework.Redis#12]
Hi,

I amusing this API and it is working perfectly. I am looking know on how to query a hash containing a list of product by object properties. For instance I want to get all Products having Category == 'Electronic'

How to achieve that using this API? I know that I can use tags but that means that will inject more data.

Best Regards
H.JAIDI

**Comment by thepirat000** [comment]
That's the way to go, if you need to index your data, you need to maintain new objects with the indexes, and that means more data. 

You can have the index as a hash, or use the tagging mechanism that internally uses hashes to map the tags to the keys.

**Comment by HaythemJ** [comment]
What I want to use is a wrapper of those native redis commands: SINTER and SUNION.

How to index properties and use above commands using the API?

**Comment by thepirat000** [comment]
SINTER and SUNION are not directly exposed by this library.
Mainly because they're not cluster-safe in the meaning that the SET keys should belong to the same hash slot.

SE.Redis provides access to that commands with the `SetCombine` method. See some [test](https://github.com/StackExchange/StackExchange.Redis/blob/29b5cc180ac560b61009ec68ea20ae1d2a0052d0/StackExchange.Redis.Tests/DatabaseWrapperTests.cs#L510) examples.

You can access the `ConnectionMultiplexer` from SE.Redis by calling the `GetConnectionMultiplexer` method on the context, for example:
```c#
var cnnMx = context.GetConnectionMultiplexer();
cnnMx.GetDatabase().SetCombine(SetOperation.Intersect, "set1", "set2")
```
