### ISSUE TITLE
HINCRBY

### ISSUE THREAD

**Issue by mrcode86** [thepirat000/CachingFramework.Redis#14]
Is that something you can add? I really miss it :)

And, thanks for a great framework.

**Comment by thepirat000** [comment]
Hi

Command that assumes a format on the values are not implemented because will work *only* for values that were serialized as simple strings (i.e. with the JSON serializer). 

If we use, for example, the default serializer (Binary compressed), HINCRBY will fail because the hash value will not be a number representation.

That's the reason because I haven't implemented those commands.

Anyway you have the possibility to use the SE.Redis API be calling the `GetConnectionMultiplexer()` method, so you can do for example:

```c#
var context = new Context("localhost:6379", new JsonSerializer());  // <-- Use the JSON serializer
// HSET hash field 100
context.Cache.SetHashed("hash", "field", 100);

// HINCRBY hash field 1
context.GetConnectionMultiplexer().GetDatabase().HashIncrement("hash", "field", 1);

// HGET hash field
context.Cache.GetHashed<int>("hash", "field").Dump();
```

**Comment by mrcode86** [comment]
Perfect, thanx.
