### ISSUE TITLE
Why are you removed Json.Net support?

### ISSUE THREAD

**Issue by nkochnev** [thepirat000/CachingFramework.Redis#2]
In beggining project you support Json.Net, but later you removed. Why?

**Comment by thepirat000** [comment]
Just to avoid the dependency with the Json.net library and let the client decide which serialization library/strategy to use.  https://github.com/thepirat000/CachingFramework.Redis/blob/master/README.md#serialization

**Comment by thepirat000** [comment]
Closing this since I've just included the Json serializer as an optional separated package: [CachingFramework.Redis.Json](https://www.nuget.org/packages/CachingFramework.Redis.Json)

Then you just use the context provided on this package:
var jsonContext = new CachingFramework.Redis.Json.Context("localhost:6379");

https://github.com/thepirat000/CachingFramework.Redis/blob/master/README.md#serialization

**Comment by nkochnev** [comment]
Thanks!
