### ISSUE TITLE
.Net Core Can not read .NET Framework 4.6 value 

### ISSUE THREAD

**Issue by kansousama** [thepirat000/CachingFramework.Redis#46]
.Net Framework 4.6
`context.Cache.SetObject(redisKey, "123456", TimeSpan.FromDays(1));`

.Net Core 2.1
`context.Cache.GetObject<string>(redisKey);`

throw "Unexpected character encountered while parsing value: . Path '', line 1, position 1."
Why?

**Comment by thepirat000** [comment]
That's because the default serialization method differs between the full framework version and the net core version. BinarySerializer vs JsonSerializer. You will need to use the same serialization method on both sides, for example by changing the full framework version to use JsonSerializer. Take a look at this issue https://github.com/thepirat000/CachingFramework.Redis/issues/26

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thepirat000** [comment]
You can now [change the default serializer](https://github.com/thepirat000/CachingFramework.Redis#default-serialization-method) globally with the static `RedisContext.DefaultSerializer` property.

For example, you could do the following on your apps startup logic to be sure the serializer is the same:

```C#
RedisContext.DefaultSerializer = new JsonSerializer();
```
