### ISSUE TITLE
\n\t is added to the key when using .GetRedisDictionary

### ISSUE THREAD

**Issue by HolopaMir** [thepirat000/CachingFramework.Redis#52]
Hello, when using fetch and set methods, fieldkeys are inserted normally, but when i use GetRedisDictionary to add values to hash, keys get extra data (\n\t) added to them.

Something like this:
```
var dict = _context.Collections.GetRedisDictionary<string, string>(hashKey);
await dict.AddAsync("somekey", "somevalue", new []{"red"}); // somekey will be saved as '\n\tsomekey'

var actual = await _context.Cache.GetHashedAllAsync<string>(hashKey);
var notWorking = actual["somekey"];
var working = actual["\n\tsomekey"]; // Should be without \n\t
```

When data added through GetRedisDictionary()
![image](https://user-images.githubusercontent.com/28385784/46593223-c44b1d00-cad2-11e8-87f3-ce285b196001.png)

When same data is added through fetch:
![image](https://user-images.githubusercontent.com/28385784/46593266-2a37a480-cad3-11e8-8d31-b992ae458960.png)

Is there something i'm doing wrong? Have you encountered this problem before?

**Comment by HolopaMir** [comment]
Repro: https://github.com/Enegia/RedisDictionaryBugRepro

**Comment by thepirat000** [comment]
I see.

The problem is that the hashed methods `GetHashed<T>()`, `ScanHashed<T>()` `GetHashedAll<T>()`, `SetHashed<T>()`, `FetchHashed<T>()` and `RemoveHashed()` assumes the **fields** are plain strings, (the fields are not serialized/deserialized but directly interpreted as strings), but the RedisDictionary always serializes its fields. 

Some of these methods have overloads that allows to specify the **field type** in order to serialize/deserialize the fields. But unfortunately the GetHashedAll doesn't have that overload. I will add the missing overloads on the next version, so you should be able to do like:

```c#
var actual = await _context.Cache.GetHashedAllAsync<string, string>(hashKey);
```

**Comment by thepirat000** [comment]
Please upgrade to latest version (10.0.2) and try with the suggested line (note you have to explicitly pass the two type parameters, the first for the fields, and the second for the values):

```c#
var actual = await _context.Cache.GetHashedAllAsync<string, string>(hashKey);
```

Feel free to comment if you're still having problems

**Comment by HolopaMir** [comment]
Yes, that fixes the problem. Thank you so much! :)
