### ISSUE TITLE
Tags TTL is not updated when KeyExpire is used

### ISSUE THREAD

**Issue by lucamnn** [thepirat000/CachingFramework.Redis#71]
When a call to KeyExpire is made, tags entries are not consequently updated. They stuck on initial TTL from the key .
So it happens that the keys are still active, but they lose the related tags.

**Comment by thepirat000** [comment]
I guess you are inserting a key related to a tag with a given TTL, and then you are updating the key TTL to a higher value.

If a key TTL is changed, the corresponding tags to which it belongs will not be affected. Since the relation is from the Tags to the Keys, but not the other way. There is no _O(1)_ way to know to which tag(s) a particular item belongs to. So the only alternative could be the client providing the tags that needs to be updated along with the item.

> The TTL for the Tag container is the maximum TTL of the items at the moment they were added to the tag. 

So for the current version I guess the only option is to re-set the value when you are updating the TTL:

```c#
ctx.Cache.SetObject(key, "the value", new [] { "tag1" }, TimeSpan.FromSeconds(5));

...

// Updates the item TTL and also the tag container TTL (if it's higher than the current TTL):
// But... this also updates the item value
ctx.Cache.SetObject(key, "the value", new[] { "tag1" }, TimeSpan.FromHours(24)); 
```

Maybe the cache provider could provide a method to update the TTL on an item and the given tags, which will be the same as calling `SetObject()` but without re-setting the value, something like this:

```c#
ctx.Cache.KeyTimeToLive(key, new[] { "tag1" });
```

I need to think a little bit more about it, any input is appreciated, will something like that work for your use case?

**Comment by thepirat000** [comment]
The version 12.0.5 includes the following overrides for `KeyTimeToLive()` and `KeyTimeToLiveAsync()` that allows to set the expiration for the tags also.

Note the tag container TTL will be the maximum TTL of its members.

```c#
Task KeyTimeToLiveAsync(string key, string[] tags, TimeSpan ttl, CommandFlags flags = CommandFlags.None);

void KeyTimeToLive(string key, string[] tags, TimeSpan ttl, CommandFlags flags = CommandFlags.None);
```c#

Please upgrade your references and re-test

**Comment by lucamnn** [comment]
It works perfectly for my use case
